trigger:
- '*'

pool:
  vmImage: 'maven'

variables:
  VmImagename: "maven"

stages:
  - stage: Build
    displayName: build app
    jobs:
      - job:
        pool: $(VmImagename)

        steps:
            - task: Maven@4
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'clean install'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                mavenVersionOption: 'Default'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false


